version: "1.0"
info:
  model: int-scaffold
packages:
- name: RockAndRollProject
  gitServerName: jlGithub
  gitUrl: https://github.com/levjason
  gitUsername: levjason
  gitBranch: main
services:
- serviceName: project.rockandroll.javaservices.Default:MakeItUpper
  packages:
  - name: RockAndRollProject
    version: "1.0"
